@StorageApi_HostAddress = https://localhost:7068

GET {{StorageApi_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{StorageApi_HostAddress}}/api/products

### 
GET {{StorageApi_HostAddress}}/api/products/3

###
POST {{StorageApi_HostAddress}}/api/products
Content-Type: application/json
{
  "name": "Beam",
  "Price": 25,
  "Category": "Materials",
  "Shelf": "B2",
  "Count": 20,
  "Description": "The wood pillars."
}
###

PATCH {{StorageApi_HostAddress}}/api/products/3
Content-Type: application/json
[
  {
    "op": "replace",
    "path": "/price",
    "value": 20
  }
]

### 
DELETE {{StorageApi_HostAddress}}/api/products/7

###
GET {{StorageApi_HostAddress}}/api/products/stats

###
GET {{StorageApi_HostAddress}}/api/products/?category=Materials

###
GET {{StorageApi_HostAddress}}/api/products?category=Tools&productname=Wrench