// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StorageApi.Migrations
{
    [DbContext(typeof(StorageApiContext))]
    partial class StorageApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StorageApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tools",
                            Count = 5,
                            Description = "Wooden handle.",
                            Name = "Hammer",
                            Price = 10m,
                            Shelf = "A1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Tools",
                            Count = 10,
                            Description = "The one with the flat head.",
                            Name = "Screwdriver",
                            Price = 5m,
                            Shelf = "A2"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tools",
                            Count = 7,
                            Description = "The one with the adjustable jaw.",
                            Name = "Wrench",
                            Price = 15m,
                            Shelf = "A3"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Tools",
                            Count = 10,
                            Description = "The one with the thoots.",
                            Name = "Saw",
                            Price = 5m,
                            Shelf = "A2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
